spring:
  config:
    activate:
      on-profile: local

  neo4j:
    uri: bolt://localhost:7688
    authentication:
      username: neo4j
      password: test1234
    security:
      encrypted: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/000-master.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: false

management:
  server:
    port: 9090
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics