spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:neo4j:bolt://localhost:7688
    username: neo4j
    password: test1234
    driver-class-name: org.neo4j.jdbc.bolt.BoltDriver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/000-master.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: false

management:
  server:
    port: 9090
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus